repos:
  # Common hooks for various checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespace from files
      - id: end-of-file-fixer    # Ensures a newline at the end of each file
      - id: check-yaml           # Validates YAML files syntax
      - id: check-json           # Validates JSON files syntax
      - id: detect-private-key   # Searches for private keys in the repository
      - id: check-added-large-files  # Prevents large files from being added to the repository
  # Code formatting with Black Jupyter
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black-jupyter
  # Linting with Flake8 and complexity checks with McCabe
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-mccabe
  # Static type checking with Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
  # Spellchecking Markdown files with cspell
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.8.2
    hooks:
      - id: cspell
